# Generated by Django 4.2 on 2025-10-27 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tieba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='贴吧名称')),
                ('description', models.TextField(max_length=1000, verbose_name='贴吧描述')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='tieba_avatars/', verbose_name='贴吧头像')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tieba_banners/', verbose_name='贴吧横幅')),
                ('member_count', models.IntegerField(default=0, verbose_name='成员数')),
                ('post_count', models.IntegerField(default=0, verbose_name='帖子数')),
                ('today_post_count', models.IntegerField(default=0, verbose_name='今日帖子数')),
                ('status', models.SmallIntegerField(choices=[(0, '待审核'), (1, '正常'), (2, '封禁'), (3, '隐藏')], default=0, verbose_name='状态')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '贴吧',
                'verbose_name_plural': '贴吧',
                'db_table': 'tieba',
            },
        ),
        migrations.CreateModel(
            name='TiebaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='分类描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '贴吧分类',
                'verbose_name_plural': '贴吧分类',
                'db_table': 'tieba_category',
            },
        ),
        migrations.CreateModel(
            name='TiebaAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('tieba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='tiebas.tieba', verbose_name='贴吧')),
            ],
            options={
                'verbose_name': '贴吧公告',
                'verbose_name_plural': '贴吧公告',
                'db_table': 'tieba_announcement',
                'ordering': ['-is_top', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tieba',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiebas.tiebacategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='tieba',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tiebas', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.CreateModel(
            name='TiebaMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(choices=[(0, '普通成员'), (1, '小吧主'), (2, '大吧主')], default=0, verbose_name='角色')),
                ('status', models.SmallIntegerField(choices=[(0, '申请中'), (1, '正常'), (2, '封禁')], default=0, verbose_name='状态')),
                ('post_count', models.IntegerField(default=0, verbose_name='发帖数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('last_active_at', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('tieba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tiebas.tieba', verbose_name='贴吧')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tieba_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '贴吧成员',
                'verbose_name_plural': '贴吧成员',
                'db_table': 'tieba_member',
                'unique_together': {('user', 'tieba')},
            },
        ),
    ]
